site_name: Censorship Bypass Guide
theme:
  name: terminal
  palette: dark

features:
  - navigation.side.indexes

nav:
  - Home: "index.md" # This will be the homepage
  - Server Side:
      - V2ray: "server/V2ray.md"
      - Hysteria 2: "server/Hysteria.md"
      - NaïveProxy: "server/Naïve.md"
      - Trojan: "server/trojan.md"
      - Kasm Workspaces: "server/Kasm.md"
      - Doge Unblocker: "server/Doge.md"
      - VPN: "server/VPN.md"
  - Support:
      - Support: "support/Support.md"
  - Misc:
      - Safety: "misc/safety.md"
      - Contacts: "misc/contacts.md"
      - Licence: "misc/licence.md"
