site_name: Censorship Bypass Guide
theme:
  name: terminal
  palette: dark

features:
  - navigation.side.indexes

markdown_extensions:
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: "index.md" # Homepage
  - Server Side:
      - V2ray: "Server/V2ray.md"
      - Hysteria 2: "Server/Hysteria.md"
      - NaïveProxy: "Server/Naïve.md"
      - Trojan: "Server/Trojan.md"
      - Kasm Workspaces: "Server/Kasm.md"
      - Doge Unblocker: "Server/Doge.md"
      - VPN: "Server/VPN.md"
  - Client Side:
      - Clients: "Client Side/Clients.md"
  - Misc:
      - Website Source Code: "https://github.com/eli32-vlc/censorshipbypassguide"
      - Gateway: "https://censordex.fr.to"
      - Free VLESS: "https://theglitchreport.qzz.io/posts/free-proxy-setup-using-render-and-vless/"
      - Support: "https://forum.7844380499.cfd"
      - Safety Note: "Misc/safety.md"
      - Contacts: "Misc/contacts.md"
      - Licence: "Misc/licence.md"
