site_name: Censorship Bypass Guide
theme:
  name: terminal
  palette: dark

features:
  - navigation.side.indexes

nav:
  - Home: "index.md" # Homepage
  - Server Side:
      - V2ray: "Server/V2ray.md"
      - Hysteria 2: "Server/Hysteria.md"
      - NaïveProxy: "Server/Naïve.md"
      - Trojan: "Server/Trojan.md"
      - Kasm Workspaces: "Server/Kasm.md"
      - Doge Unblocker: "Server/Doge.md"
      - VPN: "Server/VPN.md"
  - Client Side:
      - Client Side: "Client Side/Clients.md"
  - Misc:
      - Github Source: "Misc/GitHub.md"
      - Safety Note: "Misc/safety.md"
      - Contacts: "Misc/contacts.md"
      - Licence: "Misc/licence.md"
