site_name: Censorship Bypass Guide
theme:
  name: terminal

features:
  - navigation.side.indexes

nav:
  - Home: "index.md" # This will be the homepage
  - Guide:
      - V2ray: "guide/V2ray.md"
      - VPN: "guide/VPN.md"
      - Kasm Workspaces: "guide/Kasm.md"
  - Support:
      - Support: "support/Support.md"
  - Misc:
      - Contacts: "misc/contacts.md"
      - Licence: "misc/licence.md"
