site_name: Censorship Bypass Guide
theme:
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    logo: material/wall-fire
  name: material
  features:
    - navigation.footer

extra_css:
  - css/custom.css

features:
  - navigation.side.indexes

copyright: Copyright &copy; 2025 Zenith Rifle and Wispy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eli32-vlc/censorshipbypassguide

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - social:
      cards_layout: default

nav:
  - Home: "index.md" # Homepage
  - Server Side:
      - VLESS: "Server/VLESS.md"
      - VMESS: "Server/VMESS.md"
      - Hysteria 2: "Server/Hysteria.md"
      - NaïveProxy: "Server/Naïve.md"
      - Trojan: "Server/Trojan.md"
      - Kasm Workspaces: "Server/Kasm.md"
      - Doge Unblocker: "Server/Doge.md"
      - VPN: "Server/VPN.md"
  - Client Side:
      - Clients: "Client Side/Clients.md"
      - Networking: "Client Side/Networking.md"
  - Useful Links:
      - Website Source Code: "https://github.com/eli32-vlc/censorshipbypassguide"
      - Gateway: "https://censordex.fr.to"
      - Free VLESS: "https://theglitchreport.qzz.io/posts/free-proxy-setup-using-render-and-vless/"
      - Support: "https://forum.7844380499.cfd"
  - Misc:
      - Safety Note: "Misc/safety.md"
      - Website Privacy: "Misc/privacy.md"
      - Contacts: "Misc/contacts.md"
      - Licence: "Misc/licence.md"
