site_name: Censorship Bypass Guide
site_url: https://2305878273.7844380499.cfd # CHANGE THIS TO YOUR ACTUAL SITE ADDRESS

theme:
  name: material
  language: en
  custom_dir: overrides
  favicon: images/favicon.svg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    logo: material/wall-fire
  features:
    - navigation.footer
    - navigation.side.indexes

extra_css:
  - css/custom.css

copyright: Copyright &copy; 2025 Zenith Rifle and Wispy

extra:
  analytics:
    provider: custom
    property: foobar
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eli32-vlc/censorshipbypassguide

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          # ADD THESE TWO LINES:
          default: true
          build: true
          nav_translations:
            Home: "Home"
            Server Side: "Server Side"
            Client Side: "Client Side"
            Environments: "Environments"
            Useful Links: "Useful Links"
            Misc: "Misc"
        - locale: ru
          name: Русский
          # You should also add 'build: true' for Russian if you want it to be built
          build: true # ADD THIS LINE if you want the Russian version to be built
          nav_translations:
            Home: "Главная"
            Server Side: "Сторона сервера"
            Client Side: "Сторона клиента"
            Environments: "Среды"
            Useful Links: "Полезные ссылки"
            Misc: "Разное"
  - social:
      cards_layout: default

nav:
  - Home: "index.md" # Homepage
  - Server Side:
      - VLESS: "Server/VLESS.md"
      - VMESS: "Server/VMESS.md"
      - Hysteria 2: "Server/Hysteria.md"
      - NaïveProxy: "Server/Naïve.md"
      - Trojan: "Server/Trojan.md"
      - Kasm Workspaces: "Server/Kasm.md"
      - Doge Unblocker: "Server/Doge.md"
      - VPN: "Server/VPN.md"
  - Client Side:
      - Clients: "Client Side/Clients.md"
      - Networking: "Client Side/Networking.md"
  - Environments:
      - Fortinet: "Environments/Fortinet.md"
  - Useful Links:
      - Website Source Code: "https://github.com/eli32-vlc/censorshipbypassguide"
      - Gateway: "https://censordex.fr.to"
      - Free VLESS: "https://theglitchreport.qzz.io/posts/free-proxy-setup-using-render-and-vless/"
      - Support: "https://forum.7844380499.cfd"
  - Misc:
      - Safety Note: "Misc/safety.md"
      - Website Privacy: "Misc/privacy.md"
      - Contacts: "Misc/contacts.md"
      - Licence: "Misc/licence.md"
